language:
  ruby

rvm:
  - '2.4'
  - '2.6.0'

script:
  bundle exec rspec
before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y cloc gdal-bin gdebi-core libcurl4-openssl-dev libgdal-dev libproj-dev libxml2-dev build-essential libmysqlclient-dev libsqlite3-dev ghostscript imagemagick xpdf
after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT
 
